- name: install nginx
  hosts: Web
  become: yes
  tasks:
    - name: install nginx 
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: nginx
        state: started