- name: PLAY 1 
  hosts: localhost 
  tasks:
  - name: this PLAY1 task 
    ansible.builtin.debug:
      msg: This is Venkat's PB1


- name: Declaring the variable and using 
  hosts: localhost 
  vars:
    value1: venkat
    value2: 123
    value3: 234
  tasks:
  - name: using the varibles 
    ansible.builtin.debug: 
      msg: " value1 is {{my_name}} second value is {{value2}} third value is {{value3}}"
