- name: default value
  hosts: localhost
  
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: print {{course | default('Ansible')}}


- name: Handling String manupulation
  hosts: localhost
  vars: 
    greeting: Hello Venkat Good morning
  
  tasks:
    - name: convert the string into upper case
      ansible.builtin.debug:
        msg: print {{greeting}}  convert into upper {{greeting | upper}}


- name: Handling String manupulation in lower case
  hosts: localhost
  vars: 
    greeting: HELLO VENKAT GOOD MORNING
  
  tasks:
    - name: convert the string into lower case
      ansible.builtin.debug:
        msg: print {{greeting}}  convert into lower {{greeting | lower}}




- name: Removing dublicates from the list
  hosts: localhost
  vars:
    numbers: [1, 2, 4, 5, 1, 3, 5, 9, 4, 6]

  tasks:
    - name: print numbers 
      ansible.builtin.debug:
        msg: "from the list {{ numbers }}"

    - name: print unique numbers removing dublicates
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

  
  name: Finding min and max numbers 
  hosts: localhost
  vars:
    numbers: [1, 2, 4, 5, 1, 3, 5, 9, 4, 6]

  tasks:
    - name: print Min and Max numbers 
      ansible.builtin.debug:
        msg: "from the list : min number is {{ numbers | min }}  and max num is {{ numbers | max}} "



- name: Converting DICT int LIST 
  hosts: localhost
  vars:
    mydict: 
      name: 'Venkat'
      DOB:  '01-12-2000'
      city: 'BNG'
      PIN:  '332223'

  tasks: 
    - name: convert DICT into LIST
      ansible.builtin.debug:
        msg: print the list {{ mydict | dict2items }}