- name: Install packages 
  hosts: web
  become: yes 

  tasks:
    - name: install packages in node
      ansible.builtin.dnf:
        msg:  "{{ item }}"
        state: "{{ item.state }}"
      loop:
      - {name: 'mysql', state: 'latest'}
      - {name: 'nginx', state: 'absent'}
      - {name: 'postfix', state: 'absent'}
